global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'navidrome'
    metrics_path: <custom_metrics_path>
    static_configs:
      - targets: ['navidrome:4533']
    basic_auth:
      username: 'navidrome'
      password: '<navidrome_metrics_password>'

  - job_name: 'wud'
    metrics_path: /metrics  # Sadly fixed
    static_configs:
      - targets: ['wud:2999']
    basic_auth:
      username: '<wud_admin_user>'
      password: '<wud_admin_password>'

  - job_name: 'cadvisor'
    metrics_path: <custom_metrics_path>
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node'
    metrics_path: <custom_metrics_path>
    static_configs:
      - targets: ['node-exporter:9100']
