global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:

  # Navidrome: replace the metrics_path to match ND_PROMETHEUS_METRICSPATH you set
  - job_name: 'navidrome'
    metrics_path: /metrics
    static_configs:
      - targets: ['navidrome:4533']

  # cAdvisor (container metrics)
  - job_name: 'cadvisor'
    metrics_path: /metrics
    static_configs:
      - targets: ['cadvisor:8080']

  # node-exporter (host metrics)
  - job_name: 'node'
    metrics_path: /metrics
    static_configs:
      - targets: ['node-exporter:9100']
