services:
  telegram-bot:
    build: .
    container_name: navidrome_telegram_bot
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
      - SCHEDULE_TIME=08:00
      - LOGGING=INFO # Options: INFO, DEBUG
      - RUN_ON_STARTUP=false # Set to true for testing
      - NAVIDROME_API_VERSION=1.16.1
      - NAVIDROME_MUSIC_FOLDER=Music Library
    volumes:
      - ./data:/app/data
    secrets:
      - navidrome_url
      - navidrome_user
      - navidrome_password
      - telegram_bot_token
      - telegram_chat_id

secrets:
  navidrome_url:
    file: ./secrets/navidrome_url.txt
  navidrome_user:
    file: ./secrets/navidrome_user.txt
  navidrome_password:
    file: ./secrets/navidrome_password.txt
  telegram_bot_token:
    file: ./secrets/telegram_bot_token.txt
  telegram_chat_id:
    file: ./secrets/telegram_chat_id.txt
