services:

  grafana:
    image: grafana/grafana:12.3
    container_name: grafana
    ports:
      - "3005:${GRAFANA_PORT}"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./configs/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./configs/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana-dashboards:/var/lib/grafana/dashboards
      - grafana-storage:/var/lib/grafana
    networks:
      - navidrome
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.7.3
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=5d'
      - '--storage.tsdb.retention.size=10GB'
      - '--storage.tsdb.min-block-duration=1h'
      - '--storage.tsdb.max-block-duration=12h'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:${PROMETHEUS_PORT}"
    volumes:
      - ./configs/prometheus.yml.custom:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - navidrome
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.0
    container_name: cadvisor
    command:
      - --prometheus_endpoint=${CUSTOM_METRICS_PATH}
    ports:
      - "8080:${CADVISOR_PORT}"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw                # Only works with rw permissions
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - navidrome
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:v1.10.2
    container_name: node-exporter
    command:
      - --web.telemetry-path=${CUSTOM_METRICS_PATH}
    ports:
      - 9100:${NODE_EXPORTER_PORT}
    networks:
      - navidrome
    restart: unless-stopped

volumes:
  prometheus-data:
  grafana-storage:
