services:

  grafana:
    image: grafana/grafana:12.3
    user: ${PUID}:${PGID}
    profiles: ["monitoring"]
    container_name: grafana
    labels:
      - 'wud.tag.include=^\d+\.\d+$'
    environment:
      TZ: ${TZ}
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: false
    volumes:
      - ./configs/grafana-datasources.yml:/etc/grafana/provisioning/datasources/provisioner.yaml
      - ./configs/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/provisioner.yaml
      - ${VOLUMES_PATH}/grafana:/var/lib/grafana
      - ./grafana-dashboards:/var/lib/grafana/dashboards
    networks:
      - frontend
      - monitoring
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "curl --fail -sS http://127.0.0.1:3000/api/health >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  prometheus:
    image: prom/prometheus:v3.8.0
    user: ${PUID}:${PGID}
    profiles: ["monitoring"]
    container_name: prometheus
    labels:
      - 'wud.tag.include=^v\d+\.\d+\.\d+$'
    environment:
      TZ: ${TZ}
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=5d
      - --storage.tsdb.retention.size=10GB
      - --storage.tsdb.min-block-duration=1h
      - --storage.tsdb.max-block-duration=12h
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
    volumes:
      - ./configs/prometheus.yml.custom:/etc/prometheus/prometheus.yml:ro
      - ${VOLUMES_PATH}/prometheus:/prometheus
    networks:
      - monitoring
      - caddy-with-admin
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -q -O /dev/null http://127.0.0.1:9090/-/healthy || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  node-exporter:
    image: prom/node-exporter:v1.10.2
    profiles: ["monitoring"]
    container_name: node-exporter
    labels:
      - 'wud.tag.include=^v\d+\.\d+\.\d+$'
    environment:
      TZ: ${TZ}
    command:
      - --web.telemetry-path=${CUSTOM_METRICS_PATH}
    networks:
      - monitoring
    restart: unless-stopped
